### ISSUE TITLE
Remove some empty space from plots?

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/Currentscape#26]
Based on the plots generated for the README, it seems there is quite some empty space above and below the plots.
Could this be removed in some way, by default. (not just in the readme, but whenever a user generates a figure).
@AurelienJaquier ?

**Comment by AurelienJaquier** [comment]
I can remove the space at the bottom, and reduce the space at the top by default. But I would like to keep at least some space at the top by default in the case the user wants to add a title

**Comment by wvangeit** [comment]
Solved by #28
