### ISSUE TITLE
from currentscape.currentscape import plot_currentscape

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/Currentscape#33]
Can we please remove the requirement to use 'currentscape.currentscape'

from currentscape.currentscape import plot_currentscape

this should read:

from currentscape import plot_currentscape

I guess we need some import statements in __init__.py

What would have been even better:

import currentscape
and then people can just use:
currentscape.plot(....)

It would be good if you add the latter ability, by keeping backward compatibility with the old format.

**Comment by wvangeit** [comment]
@AurelienJaquier could you have a look at this? Once that is done, I think we can do an 'official' release of currentscape.

**Comment by AurelienJaquier** [comment]
Sure, doing it

**Comment by wvangeit** [comment]
Fixed
